version: '3.1'
services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - 5000:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
